name: HelloApp
options:
  bundleIdPrefix: com.test
targets:
  HelloApp:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources: [HelloApp/HelloApp]
    info:
      path: HelloApp/HelloApp/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.test.helloapp
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
